deep_learning_model: model_b_cnn_bilstm_highway
model_paramters:
  convs:
  - 3
  - 5
  - 7
  - 11
  - 21
  dense_size: 1000
  dropout_rate: 0.5
  features_to_use:
  - onehot
  - pssm
  filter_size: 256
  lr: 0.001
  lstm_size: 1000
  use_CRF: false
run_parameters:
  domain_name: cnn_bilstm_highway
  epochs: 100
  gpu: 1
  patience: 5
  setting_name: pssm_onhot
  test_batch_size: 100
  train_batch_size: 64
